import { InteriorPage } from "../components/site-chrome";
const programs = [
  ["01", "Learn", "AI & Engineering Education", "Project-based learning in responsible AI, coding, robotics, data, and emerging technologies, culminating in portfolio work and showcases.", "Curriculum planning and partner conversations", "Student learning sessions and full cohort curriculum"],
  ["02", "Fund", "Completion Support", "Funding navigation, technology, transportation, emergency aid, advising, and practical support that remove barriers beyond tuition.", "Support-model design and resource mapping", "Coordinated wraparound support for enrolled students"],
  ["03", "Grow", "Mentorship", "Sustained one-to-one and group relationships with Black and Latino professionals, educators, near peers, and industry leaders.", "Mentoring design and prospective mentor interest", "Prepared mentor matches and cohort programming"],
  ["04", "Experience", "Paid Experience", "Employer-hosted projects, job shadows, workplace readiness, and paid internships that build confidence, networks, and references.", "Employer outreach and internship design", "Paid projects, job shadows, and internships"],
  ["05", "Lead", "Transfer & Career Launch", "Resume and interview coaching, employer introductions, engineering transfer navigation, and continued support into high-growth careers.", "College and employer pathway planning", "Transfer support, career coaching, and verified next steps"],
];
export default function Programs() { return <InteriorPage eyebrow="Programs" title="Five supports. One connected pathway." lead="These program pillars describe the pathway we are building. Full delivery begins with the 2027 pilot cohort; current work centers on partners, design, and readiness."><section className="availabilitySummary" aria-label="Program availability"><article><span className="availabilityBadge now">Available now</span><h2>Help shape the model.</h2><p>Partner conversations, interest list, mentoring design, curriculum planning, and feedback from students and families.</p><a href="/get-involved#interest-form">Join the interest list →</a></article><article><span className="availabilityBadge future">Coming in 2027</span><h2>Full pilot delivery.</h2><p>Student cohort enrollment, learning experiences, mentor matches, paid internships, wraparound support, and the complete pathway.</p><a href="/get-involved#partners">Partner for the pilot →</a></article></section><section className="contentSection programPageGrid">{programs.map(([number, tag, title, copy, now, future]) => <article key={number}><div className="programCardTop"><span className="programNumber">{number}</span><p className="eyebrow">{tag}</p></div><h2>{title}</h2><p>{copy}</p><dl className="phaseList"><div><dt>Now</dt><dd>{now}</dd></div><div><dt>2027 pilot</dt><dd>{future}</dd></div></dl></article>)}</section><section className="ctaPanel"><div><p className="eyebrow">Designed for persistence</p><h2>Support continues from first spark to first opportunity.</h2></div><a className="button buttonGold" href="/get-involved#interest-form">Join the interest list →</a></section></InteriorPage>; }
