import { InteriorPage } from "../components/site-chrome";
const steps = [
  ["01", "Discover", "See yourself in the future", "Welcoming introductions make AI and engineering relevant, creative, and possible.", "Listening sessions, outreach planning, and partner recruitment", "Cohort orientation and introductory AI and engineering experiences"],
  ["02", "Build", "Turn curiosity into capability", "Projects, coaching, and collaborative learning develop responsible-AI fluency and portfolio evidence.", "Curriculum design and college/employer alignment", "Project-based learning, coaching, and portfolio development"],
  ["03", "Connect", "Grow a trusted network", "Mentors, peers, colleges, employers, and community organizations create belonging, guidance, and relationships.", "Mentoring design and prospective partner conversations", "Mentor matches, peer community, and partner-led sessions"],
  ["04", "Experience", "Apply skills in the real world", "Paid projects, research, job shadows, and internships translate learning into professional confidence.", "Internship model design and employer outreach", "Paid projects, research, job shadows, and internships"],
  ["05", "Launch", "Move into opportunity", "Engineering transfer, credentials, career coaching, and employer connections create momentum.", "Transfer-map, support, and career-pathway planning", "Supported transfer, credential, internship, apprenticeship, or employment next steps"],
];
export default function Pathways() { return <InteriorPage eyebrow="The student journey" title="Discover. Build. Connect. Experience. Launch." lead="Participants will enter where they are and move through a connected pathway designed to make the next step visible, supported, and achievable."><section className="availabilitySummary" aria-label="Pathway availability"><article><span className="availabilityBadge now">Available now</span><h2>Planning and partnership.</h2><p>Interest list, community feedback, college and employer conversations, mentoring design, curriculum planning, and first-cohort readiness.</p></article><article><span className="availabilityBadge future">2027 pilot launch</span><h2>The full student journey.</h2><p>Cohort enrollment, AI and engineering learning, wraparound support, mentor matches, paid experience, transfer navigation, and career launch.</p></article></section><section className="contentSection journeyList">{steps.map(([number, name, title, copy, now, future]) => <article key={number}><span>{number}</span><div><p className="eyebrow">{name}</p><h2>{title}</h2><p>{copy}</p><dl className="phaseList"><div><dt>Now</dt><dd>{now}</dd></div><div><dt>2027 pilot</dt><dd>{future}</dd></div></dl></div></article>)}</section><section className="contentSection splitFeature partnerNetwork"><div><p className="eyebrow">Greater Boston pilot</p><h2>Education and industry moving together.</h2></div><div><p>Trusted community organizations can recruit and support students. Public community colleges can provide accessible entry points. MassTransfer and public universities can support clearer engineering transfer routes. Professionals can mentor. Employers can offer projects, internships, and career exposure.</p><p>Project Interlock will coordinate the pathway, measure progress, and help each participant identify a concrete education, credential, internship, apprenticeship, or employment next step.</p></div><p className="partnerNote">Named partners and logos will appear as agreements are finalized. Institutions referenced in planning materials are proposed prospects or priority outreach targets unless a written agreement is announced.</p></section></InteriorPage>; }
